### ISSUE TITLE
Support filter nested collection

### ISSUE THREAD

**Issue by MichaelKoch11** [turkraft/spring-filter#216]
It would be a nice feature or I doest find it yet to filter nested collection.

Like in the Live Example to filter Company with 

(id < 10 and employees.maritalStatus: "unknown")
curl -X 'GET' \
  'https://spring-filter.herokuapp.com/company?filter=id%20%3C%2010%20and%20employees.maritalStatus%3A%22unknown%22' \
  -H 'accept: */*'

Expected Output
```json
[
  {
    "id": 4,
    "name": "Huel Inc",
    "industry": {
      "id": 3,
      "name": "Capital Markets"
    },
    "employees": [
      {
        "id": 11,
        "firstName": "Johana",
        "lastName": "Crona",
        "birthDate": "13-09-1980",
        "maritalStatus": "unknown",
        "salary": 2301
      },
      {
        "id": 16,
        "firstName": "Cora",
        "lastName": "Lebsack",
        "birthDate": "18-10-1961",
        "maritalStatus": "unknown",
        "salary": 5783
      }
    ]
  }
]
```

In my own example with one Entity and 3 Elements in nested collection i got 3 times the same response

**Comment by ghulamemustafa** [comment]
This is the only limitation I have faced so-far in the project. Please support :)

**Comment by torshid** [comment]
Hey @MichaelKoch11 @ghulamemustafa

I think that this is out of the scope of the project. The goal is to apply filtering criteria to a collection (e.g. _car_ table) in order to filter the elements of that specific collection (as it is with SQL queries).
Your query actually means `get me the companies which have at least one employee which has the marital status 'unknown'`.

In this specific case you could make a request to the employee API: `employee?filter= company.id < 10 and maritalStatus : 'unknown'`, which will effectively only return employees with the marital status _unknown_.

If you have an idea on how we could achieve your requirement, I would be glad to hear that.

Also please do note that there are other pending issues, you can always [sponsor](https://github.com/sponsors/torshid) me so that I can dedicate more time to feature requests.

Thank you.

**Comment by ghulamemustafa** [comment]
@torshid  I am a little confused here on how is this out of the scope as we're unable to filter `company` based on its `employes`. Also the example you gave about `employee` API doesn't fulfil the orignal goal i.e filter `company`.

**Comment by torshid** [comment]
@ghulamemustafa I think that there is a misunderstanding here. @MichaelKoch11 wanted to filter employees of companies, not companies based on employees.

As I said earlier, the search query Michael shared is valid and correctly filters companies based on employees, but it does not apply a second filter to the employee collection (which is what he requested: get companies according to some criteria and filter the employees of these companies based on other criteria).

It would be nice if you can provide your search query and tell what you are trying to achieve exactly.

Thanks.

**Comment by ghulamemustafa** [comment]
I just realized that the confusion was on my side (my bad). I just want to filter the companies based on the employees attributes.
eg: 
`get me the companies which have at least one employee which has the marital status 'unknown'`

**Comment by torshid** [comment]
@ghulamemustafa `get me the companies which have at least one employee which has the marital status 'unknown'` is equivalent to `/company?filter= employees.maritalStatus : 'unknown'`.

Closing the issue as the original request is out of scope.
