### ISSUE TITLE
Non-compliant urlenconding like

### ISSUE THREAD

**Issue by marcopag90** [turkraft/spring-filter#56]
While playing with comparators, i found a problem with the ~ comparator.
The query LIKE syntax doesn't work as expected and the problem is not the query itself, but the expression:
catalog.name ~ 'electronic%'. 
Without a proper url encoding of the % character to the compliant %25, the query fails because the % doesn't get past the request.
Looking at the rsql example from https://www.baeldung.com/rest-api-search-language-rsql-fiql, you can see that the LIKE comparator is the * in the query string. 
We all know that url encoding is a must have, but maybe it could be easily avoided this way.

Anyway, i wanted to give you my congratulations for this library, i've been looking for a REST API with a model driven approach fully integrated with Spring and this is the first in months of research which allows to setup a nice query language with JPA 👯‍♂️ !

**Comment by torshid** [comment]
Thanks for your contribution. :)

The origin of the `%` character is actually JPA itself, that's the character it uses for the like function. As you can see here I simply call the builder's like method without transforming the inputs (besides uppercasing):
```java
return criteriaBuilder.like(criteriaBuilder.upper((Expression) leftExpression),
            criteriaBuilder.upper((Expression<String>) rightExpression));
```

The `%` character should not be a problem if it is properly encoded to `%25` when calling the API, since Spring decodes it back naturally. For example, it works fine with Spring's RestTemplate, Postman (encodes by default), or [Swagger UI](https://spring-filter.herokuapp.com).

However I would like to have more info on your use case, which client are you using?

Since it seems to be a *standart* to use the asterisk, I just released a new version ([0.9.5](https://github.com/turkraft/spring-filter/releases/tag/0.9.5)) with support for it.

That's out off topic but how did you find the repo? :)
I have also written [a post on Medium](https://torshid.medium.com/easily-filter-entities-in-your-spring-api-f433537cfd41) some time ago, would really appreciate if you can share it.

**Comment by marcopag90** [comment]
Mhh that's strange, maybe i need to dig around some options with the client, as i was using Postman and i had to manually encode with %25 in the url to make it work, that's why i opened the issue.
Yea you are right, i know it's a JPA built-in feature (well, JPA itself just converts the parameter to a sql query in the criteria).
I think different libraries use the asterisk to avoid url enconding problems from the beginning.
I wanted something that could use JPA Repositories and entity graphs, to avoid hibernate n+1 queries when joining data and handle LAZY objects, and your library works like a charm :).

Anyways...I'm definitely sharing it dude👍 .
I found your repo from this post https://github.com/jirutka/rsql-parser/issues/29, as i was looking for a library for a microservice ecosystem built on top of Spring Framework, with the ability to work with nested objects and complex query critera.

**Comment by torshid** [comment]
Thanks again. :)
Feel free to open issues/ask for new features.

**Comment by torshid** [comment]
By the way you are right, I just remembered that Postman does not encode by default as I had the same issue, this option can be turned on though.
