### ISSUE TITLE
Variadic functions

### ISSUE THREAD

**Issue by torshid** [turkraft/spring-filter#76]
#75

`concat(firstName, concat(' ', lastName))` will then be simplified to `concat(firstName, ' ', lastName)`.

**Comment by albertodiazsaez** [comment]
I think the list should be separated with `,` instead of `+`. In code it's easier to create a list of params separated with commas to construct the concat that with `+`, but keeping the simplified version you mentioned:

`concat(firstName, ' ', lastName):'SearchTerm'`

And, because spaces it's going to be very common for a concat, maybe a `spaceConcat(firstName, lastName)`that automatically adds spaces between fields?

I do not understand what you mean by numbers, it should be possible with `concat('1', '2')` to get `12`, what is the advantage of `concat(1,2)`?

**Comment by torshid** [comment]
Good suggestion. I think that the comma separator is a better option too. I will try to implement a generic solution soon.

**Comment by torshid** [comment]
I am sorry for not being clear about 'numbers', it was supposed to be equivalent to the `sum` function when used with numbers, it has no relation to concatenation. :)

**Comment by albertodiazsaez** [comment]
No worries :P

I think it's confusing to use the concat() for two separated functions depending on the input.

I do not understand the functionality of it tho, if you put concat(1,2), what will be done with the resulting 3?

**Comment by torshid** [comment]
No, numbers are not supposed to be used with the concat function, this one can only accept strings. :D
The `+` operator can possibly used with numbers for addition, and with strings for concatenation.

**Comment by albertodiazsaez** [comment]
Ah, ok, so using `+` when working with numbers in all the filters, right?

If that's the case, the other main operators (`-` `/` `*`) should work as well.

**Comment by torshid** [comment]
Yes. You are right about implementing the other operators. But mathematical operations will have no use case I guess, so I am leaving this idea for now. I will only implement the commas for variadic functions.

**Comment by torshid** [comment]
@albertodiazsaez Just released version https://github.com/turkraft/spring-filter/releases/tag/1.0.3, you may now do `concat(firstName, ' ', lastName):'SearchTerm'` :)
